version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce

  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basketdb:
    image: redis:alpine

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discountdb:
    image: postgres

  discountdb.pgAdmin:
    image: dpage/pgadmin4

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  orderingdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  orderingmessagebroker:
    image: rabbitmq:3-management-alpine

volumes:
  mongo_data:
  redis_data:
  portainer_data:
  postgres_data:
  postgresadmin_data:
  sqlserver_data:
  rabbitmq_data: