version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    depends_on:
      - catalogdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8001:80"
 
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/db

  basket.api:
    container_name: basket.api
    depends_on:
      - basketdb
      - orderingmessagebroker
      - discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CachingSettings:ServerAddress=basketdb:6379"
      - "DiscountApiIntegrationSettings:ServiceAddress=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://admin:admin1234@orderingmessagebroker"
    ports:
      - "8002:80"

  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin1234
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  discountdb.pgAdmin:
    container_name: discountdb.pgAdmin
    restart: always
    depends_on:
      - discountdb
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    volumes:
      - postgresadmin_data:/root/.pgadmin

  discount.api:
    container_name: discount.api
    depends_on:
      - discountdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:Server=discountdb"
      - "DatabaseSettings:Port=5432"
      - "DatabaseSettings:DatabaseName=DiscountDb"
      - "DatabaseSettings:SchemaOwner=public"
      - "DatabaseSettings:TableName=Coupon"
      - "DatabaseSettings:UserId=admin1234"
      - "DatabaseSettings:Password=admin"
    ports:
      - "8003:80"

  discount.grpc:
    container_name: discount.grpc
    depends_on:
      - discountdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:Server=discountdb"
      - "DatabaseSettings:Port=5432"
      - "DatabaseSettings:DatabaseName=DiscountDb"
      - "DatabaseSettings:SchemaOwner=public"
      - "DatabaseSettings:TableName=Coupon"
      - "DatabaseSettings:UserId=admin1234"
      - "DatabaseSettings:Password=admin"
    ports:
      - "8004:80"

  orderingdb:
    container_name: orderingdb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  orderingmessagebroker:
    container_name: orderingmessagebroker
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin1234
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
     - rabbitmq_data:/var/opt/rabbitmq

  ordering.api:
    container_name: ordering.api
    depends_on:
      - orderingdb
      - orderingmessagebroker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderingdb;Database=OrdersDb;User id=sa;Password=yourStrong(!)Password"
      - "EventBusSettings:HostAddress=amqp://admin:admin1234@orderingmessagebroker"
    ports:
      - "8005:80"